name: ${name}
main: com.volmit.adapt.Adapt
version: ${version}
authors: [ NextdoorPsycho, Cyberpwn,  Vatuu ]
api-version: ${apiversion}
softdepend: [ PlaceholderAPI, WorldGuard ]
libraries:
  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
  - org.apache.commons:commons-lang3:3.12.0
  - com.google.code.gson:gson:2.8.9
  - com.elmakers.mine.bukkit:EffectLib:9.4
commands:
  adapt:
    aliases: [ a, ada ]